version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: webapp-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge

volumes:
  postgres_data: